# Generated by Django 3.0.4 on 2020-03-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_report_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.TextField(default='address', max_length=25),
            preserve_default=False,
        ),
    ]
