# Generated by Django 3.0.4 on 2020-03-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200329_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
